### ISSUE TITLE
Media group

### ISSUE THREAD

**Issue by vlab97** [HeimanPictures/Feedback-bot#7]
Hi! Is it possible to implement sending a group of media in one message? That is, without separation according to different messages?![image](https://user-images.githubusercontent.com/44323817/212543908-7bdd6747-9373-4dfc-add8-79a99480ed6f.jpeg)

**Comment by HeimanPictures** [comment]
Dear @vlab97,
I have added the feature but has some small bug, which will be solved when ever i am free. 
Thank you

**Comment by vlab97** [comment]
> Dear @vlab97, I have added the feature but has some small bug, which will be solved when ever i am free. Thank you

You left the bot token and other confidential information in the comment

**Comment by vlab97** [comment]
2023-02-22 16:55:31,575 - pyrogram.dispatcher - ERROR - Invalid parse mode "html"
Traceback (most recent call last):
  File "D:\SOFT\Bot\Feedback-bot-Heroku\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\SOFT\Bot\Feedback-bot-Heroku\bot.py", line 127, in start
    await bot.send_message(
  File "D:\SOFT\Bot\Feedback-bot-Heroku\lib\site-packages\pyrogram\methods\messages\send_message.py", line 124, in send_message
    message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
  File "D:\SOFT\Bot\Feedback-bot-Heroku\lib\site-packages\pyrogram\utils.py", line 354, in parse_text_entities
    text, entities = (await client.parser.parse(text, parse_mode)).values()
  File "D:\SOFT\Bot\Feedback-bot-Heroku\lib\site-packages\pyrogram\parser\parser.py", line 54, in parse
    raise ValueError(f'Invalid parse mode "{mode}"')
ValueError: Invalid parse mode "html"
